x = input("Digite algo: ")
print("O valor digitado é: ")
print("Tipo: {}".format(type(x)))
print("Numerico: {}".format(x.isnumeric()))
print("Alfabetico: {}".format(x.isalpha()))
print("Alfanumerico: {}".format(x.isalnum()))
print("Maiusculo: {}".format(x.isupper()))
print("Minusculo: {}".format(x.islower()))
